name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta diariamente a medianoche
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generar Animación de la Serpiente
        uses: Platane/snk@v3
        with:
          github_user_name: xscriptorcode  # Reemplaza con tu nombre de usuario
          outputs: |
            dist/github-snake.svg?color_snake=orange&color_dots=#010,#020,#050,#0a0,#0f0&color_bg=black
      - name: Publicar Animación Generada
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

