name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: xscriptorcode
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.svg?color_snake=orange&color_dots=#010,#020,#050,#0a0,#0f0&color_bg=black

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
